services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    networks:
      - caddy
    volumes:
      - /apps/uptime-kuma/data:/app/data
    labels:
      caddy: uptime.ilr.cornell.edu
      caddy.reverse_proxy: "{{upstreams 3001}}"
    restart: unless-stopped

networks:
  caddy:
    external: true
