services:
  whoami:
    image: traefik/whoami
    networks:
      - caddy
    labels:
      caddy: verdandi.ilr.cornell.edu
      caddy.reverse_proxy: "{{upstreams 80}}"

networks:
  caddy:
    external: true
